# Repo-relative paths for result/artifact folders. These are cached
# outputs and figures generated by the Experiment_*/Abblation_*/Sweep_*
# scripts and re-read by later scripts (e.g. grid-search configs, SHAP
# caches) - they live under results/ in this repo, so they resolve the
# same way for every clone and don't need a machine-specific entry in
# local_paths.py.
#
# Raw PulseDB/VitalDB data is not shipped in the repo (see dataset.txt),
# so PULSE_DB_SUP_DIR is still supplied via local_paths.py.

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = REPO_ROOT / "results"

PERFORMANCE_RESULTS_PAPER = RESULTS_DIR / "performance"
GS_RESULT_PAPER = RESULTS_DIR / "grid_search"
SHAP_RESULTS_PAPER = RESULTS_DIR / "shap"
DEMOG_RESULTS_PAPER = RESULTS_DIR / "demographics"
ABBLATION_RESULTS_PAPER = RESULTS_DIR / "ablation"
FIGURES_PAPER = RESULTS_DIR / "figures"
DISTRIBUTION_ANALYSIS_DIR = RESULTS_DIR / "distribution_analysis"
THRESHOLD_SWEEP_ML_RESULTS = RESULTS_DIR / "threshold_sweep"
ALPHA_BETA_SWEEP_ML_RESULTS = RESULTS_DIR / "alpha_beta_sweep"
FILTERING_SENSITIVITY_DIR = RESULTS_DIR / "filtering_sensitivity"

# Used by Scripts/fiducial_quality_filtering/run_pipeline.py for its small
# descriptive report outputs (xlsx/csv). The .h5 outputs from that same
# script (quality reports, filtered/cleaned feature files) are NOT here -
# they're data-sized and stay in DATA_DIR, see that folder's local_paths.py.
QUALITY_FILTERING_REPORTS_DIR = RESULTS_DIR / "quality_filtering"
